samples_LOW = 20        # Low range of samples per data set in plot (3 datasets would have min of 60)
samples_HIGH = 250      # High range of samples per data set in plot
leading_coe_LOW = 1     # one degree polynomial low end leading coefficient range 
leading_coe_HIGH = 20    # one degree polynomial high end leadig coefficient range
POS_NEG = 1             # positive or negative leading coeeficient (1 for positive, -1 for negative)
constant_LOW = 0        # one degree polynomial low end of constant range
constant_HIGH = 80      # one degree polynomial high end of constant range
STD_LOW = 1             # standard deviation low end of range for gaussian noise added to data points
STD_HIGH = 100           # standard deviation high end of range for gaussian noise added to data points
POLY = "(m*x) + b"      # equation to scatterplot
Y_INT_LOW = -100         # low end of y intercept
Y_INT_HIGH = 300         # high end of y intercept
DATASETS_PER_PLOT = 1   # number of datasets to be plotted on each plot
TOTAL_PLOTS = 1000        # total plots to plot and save into PATH with these hyper parameters
REMOVE_TREE = False     # default to remove the preexisting folder for the new saved plots
CLASS_LABEL = 'one_strong_pos' # class label